trigger:
  - master
  - develop

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: Unsplash
  - name: rootDir
    value: "pet-calendar"
  - name: buildDir
    value: "$(rootDir)/build"

steps:
  - template: azure-template.yml
    parameters:
      buildConfiguration: "QA"
